site_name: Apuntes UA
site_url: https://igl38-ua.github.io/apuntesUA
# repo_url: "https://github.com/igl38-ua/apuntesUA"
theme:
  name: material
  features:
    - navigation.tabs
    - toc.follow
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2-6
      title: "Contenido"
  - pymdownx.arithmatex
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - nl2br

hooks:
  - hooks.py

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/igl38-ua/apuntesUA
#   copyright: "© 2025 igl38-ua. Todos los derechos reservados."

extra_css:
  - assets/styles.css

nav:
  - Inicio: index.md
  - ADA:
    - ADA HUB: ADA/ADA HUB.md
    - Conceptos clave: ADA/Conceptos clave.md
    - Cálculo de complejidades básicas: ADA/Cálculo de complejidades básicas.md
    - Complejidad y notación asintótica: ADA/Complejidad y notación asintótica.md
    - Ecuaciones de recurrencia: ADA/Ecuaciones de recurrencia.md
    - Cotas: ADA/Cotas.md
    - Tipos del Problema de la mochila: ADA/Tipos del Problema de la mochila.md
    - Divide y vencerás:
      - Divide y vencerás: ADA/Divide y vencerás/Divide y vencerás.md
      - QuickSort: ADA/Divide y vencerás/QuickSort.md
      - MergeSort: ADA/Divide y vencerás/MergeSort.md
      - HeapSort: ADA/Divide y vencerás/HeapSort.md
      - Torres de Hanoi: ADA/Divide y vencerás/Torres de Hanoi.md
      - Corte de tubos: ADA/Divide y vencerás/Corte de tubos.md
    - Programación dinámica:
      - Programación dinámica: ADA/Programación dinámica/Programación dinámica.md
      - Programación dinámica iterativa: ADA/Programación dinámica/Programación dinámica iterativa.md
      - Coeficiente binomial: ADA/Programación dinámica/Coeficiente binomial.md
      - El problema de la mochila (knapsack problem): ADA/Programación dinámica/El problema de la mochila (knapsack problem).md
    - Algoritmos voraces:
      - Algoritmos voraces: ADA/Algoritmos voraces/Algoritmos voraces.md
      - El problema de la mochila continua: ADA/Algoritmos voraces/El problema de la mochila continua.md
      - El problema de la mochila discreta (sin fraccionamiento): ADA/Algoritmos voraces/El problema de la mochila discreta (sin fraccionamiento).md
      - El problema del cambio: ADA/Algoritmos voraces/El problema del cambio.md
      - Árboles de recubrimiento de coste mínimo:
        - Árboles de recubrimiento de coste mínimo: ADA/Algoritmos voraces/Árboles de recubrimiento de coste mínimo/Árboles de recubrimiento de coste mínimo.md
        - Algoritmo de Prim: ADA/Algoritmos voraces/Árboles de recubrimiento de coste mínimo/Algoritmo de Prim.md
        - Algoritmo de Kruskal: ADA/Algoritmos voraces/Árboles de recubrimiento de coste mínimo/Algoritmo de Kruskal.md
        - Conjuntos disjuntos (Disjoint-set): ADA/Algoritmos voraces/Árboles de recubrimiento de coste mínimo/Conjuntos disjuntos (Disjoint-set).md
    - Back tracking:
      - Back tracking: ADA/Back tracking/Back tracking.md
      - El problema de la mochila (general): ADA/Back tracking/El problema de la mochila (general).md
      - El problema de las n reinas: ADA/Back tracking/El problema de las n reinas.md
      - Permutaciones: ADA/Back tracking/Permutaciones.md
      - Viajante de comercio: ADA/Back tracking/Viajante de comercio.md
    - Ramificación y poda:
      - Ramificación y poda: ADA/Ramificación y poda/Ramificación y poda.md

  - REDES: 
    - REDES HUB: REDES/REDES HUB.md
    - Tema 1: REDES/TEMA 1/TEMA 1.md
    - Tema 2. Arquitectura de red: REDES/TEMA 2/TEMA 2.md
    - Tema 3. Nivel físico: 
      - Tema 3: REDES/TEMA 3/!TEMA 3.md
      - Modulaciones y usos: REDES/TEMA 3/Modulaciones y usos.md
      - Multiplexión: REDES/TEMA 3/Multiplexión.md
      - Medios de transmisión: REDES/TEMA 3/Medios de transmisión.md
      - Resumen comparativo de las técnicas de modulación y multiplexión: REDES/TEMA 3/Resumen comparativo de las técnicas de modulación y multiplexión.md
    - Tema 4. Nivel de enlace: 
      - Tema 4: REDES/TEMA 4/!TEMA 4.md
      - Mecanismos de verificación de tramas: 
        - SVT: REDES/TEMA 4/MVT/!MVT.md
        - FCS (Frame Check Sequence): REDES/TEMA 4/MVT/FCS (Frame Check Sequence).md
        - Paridad: REDES/TEMA 4/MVT/Paridad.md
        - CRC (Cyclic Redundancy Check): REDES/TEMA 4/MVT/CRC (Cyclic Redundancy Check).md
        - Suma de verificación (Checksum): REDES/TEMA 4/MVT/Suma de verificación (Checksum).md
      - Protocolos de parada y espera: REDES/TEMA 4/Protocolos de parada y espera.md
      - Protocolos de ventana deslizante: REDES/TEMA 4/Protocolos de ventana deslizante.md
      - Redes LAN 1 - Normas IEEE 802.X: REDES/TEMA 4/Redes LAN 1 - Normas IEEE 802.X.md
      - Redes LAN 1.1 - IEEE 802.11x LAN Inalámbricas: REDES/TEMA 4/Redes LAN 1.1 - IEEE 802.11x LAN Inalámbricas.md
    - Tema 5. Nivel de red: REDES/TEMA 5/TEMA 5.md
    - Tema 6. Nivel de transporte: REDES/TEMA 6/TEMA 6.md
    - Tema 7. Acceso a servicios de internet: REDES/TEMA 7/TEMA 7.md
    - Cabeceras protocolos: REDES/Cabeceras.md
    - Protocolos:
      - RIP: REDES/Protocolos/RIP.md
      - OSPF: REDES/Protocolos/OSPF.md
      - BGP: REDES/Protocolos/BGP.md
    - Formulario: REDES/Formulario.md
    - Esquema de contenido: REDES/Esquema de contenido.md
    - Estándares de redes: REDES/TEMA 4/Estándares de redes LAN.md

  - PPSS:
    - PPSS HUB: PPSS/PPSS HUB.md
    - S01 - Pruebas del software: PPSS/S01 - Pruebas del software.md
    - S02 - Pruebas de Caja Blanca: PPSS/S02 - Pruebas de Caja Blanca.md
    - S03 - Drivers: PPSS/S03 - Drivers.md
    - S04 - Pruebas de Caja Negra: PPSS/S04 - Pruebas de Caja Negra.md
    - S05 - Dependencias: 
      - S05.1 - Dependencias externas 1 (STUBs): PPSS/S05 - Dependencias externas 1 (STUBs).md
      - S05.2 - Flujo de dependencias y ficheros en STUBs: PPSS/S05.1 - Flujo de dependencias y ficheros en STUBs.md
    - S06 - Dependencias externas 2 (mocks): PPSS/S06 - Dependencias externas 2 (mocks).md
    - S07 - Integración: PPSS/S07 - Integración.md
    - S08 - Pruebas de aceptación 1:
      - S08.1 - Pruebas de sistema vs aceptación: PPSS/S08 - Pruebas de sistema vs aceptación.md
      - S08.2 - Page Object y Page Factory: PPSS/S08.1 - Page Object y Page Factory.md
    - S09 - Pruebas de aceptación 2: PPSS/S09 - Pruebas de aceptación 2.md
    - S10 - Análisis de pruebas: PPSS/S10 - Análisis de pruebas.md
    - Maven:
      - Artefactos maven: PPSS/Maven/Artefactos maven.md
      - Fases, Goals y Plugins: PPSS/Maven/Fases, Goals y Plugins.md
      - pom.xml: PPSS/Maven/pom.xml.md
    - Parciales:
      - Parcial 1: PPSS/Parcial 1.md
      - Parcial 2: PPSS/Parcial 2.md
